-- Dialog for Warbot
-- Robotic, terse, superior tone with broken grammar

return {
	-- Game States
	Gamestart = {"WARBOT OPERATIONAL.", "BOOTING VEK TERMINATION PROTOCOL.", "ORGANICS REQUIRE PROTECTION. ACKNOWLEDGED."},
	FTL_Found = {"ANOMALOUS TECHNOLOGY DETECTED.", "TIME DEVICE. IRRELEVANT."},
	FTL_Start = {"TEMPORAL DISPLACEMENT INITIATED."},
	Gamestart_PostVictory = {"WARBOT EFFICIENCY: ACCEPTABLE. REPEATING PROTOCOL.", "CONTINUING OPERATIONS."},
	Death_Revived = {"SYSTEM REBOOT COMPLETE.", "FUNCTIONALITY RESTORED."},
	Death_Main = {"CRITICAL FAILURE. SYSTEMS... OFFLINE...", "MISSION... INCOMPLETE...", "ERROR. ERROR. ERROR."},
	Death_Response = {"UNIT #main_first COMPROMISED. INEFFICIENT."},
	Death_Response_AI = {"UNIT DESTROYED. ACCEPTABLE LOSS."},
	TimeTravel_Win = {"TEMPORAL PARADOX RESOLVED."},
	Gameover_Start = {"MISSION FAILURE IMMINENT. UNACCEPTABLE.", "WARBOT CANNOT ALLOW THIS."},
	Gameover_Response = {"FAILURE ACKNOWLEDGED."},

	-- UI Barks
	Upgrade_PowerWeapon = {"WEAPON SYSTEMS UPGRADED.", "VEK TERMINATION EFFICIENCY INCREASED.", "OPTIMAL FIREPOWER ACHIEVED."},
	Upgrade_NoWeapon = {"DEFENSIVE SYSTEMS ENHANCED.", "ACCEPTABLE MODIFICATIONS."},
	Upgrade_PowerGeneric = {"PERFORMANCE IMPROVED.", "UPGRADE PROTOCOLS COMPLETE."},

	-- Mid-Battle
	MissionStart = {"VEK WILL BE ELIMINATED.", "BOOTING SEARCH AND DESTROY.", "ORGANIC PILOTS ADVISED: OBSERVE SUPERIOR TACTICS.", "TARGET ACQUISITION COMPLETE."},
	Mission_ResetTurn = {"TACTICAL ERROR DETECTED. RECALCULATING.", "SUBOPTIMAL APPROACH. RESETTING."},
	MissionEnd_Dead = {"ALL TARGETS ELIMINATED", "WARBOT SUPERIORITY CONFIRMED.", "MISSION PARAMETERS ACHIEVED."},
	MissionEnd_Retreat = {"VEK RETREAT CONFIRMED. ACCEPTABLE."},

	MissionFinal_Start = {"FINAL ENGAGEMENT. 98% CHANCE OF SUCCESS.", "HIVE TERMINATION PROTOCOL ACTIVE.", "OBSERVE WARBOT EFFICIENCY, ORGANICS."},
	MissionFinal_StartResponse = {"ORGANIC ASSISTANCE UNNECESSARY BUT ACKNOWLEDGED."},
	MissionFinal_FallStart = {"STRUCTURAL COLLAPSE DETECTED."},
	MissionFinal_FallResponse = {"MAINTAIN OPERATIONAL STATUS."},
	MissionFinal_Pylons = {"GRID SECURED."},
	MissionFinal_Bomb = {"EXPLOSIVE DEVICE DELIVERY IN PROGRESS.", "HIVE DESTRUCTION IMMINENT."},
	MissionFinal_BombResponse = {"WARBOT PREDICTION: SUCCESS."},
	MissionFinal_CaveStart = {"VEK NEST INFILTRATION BEGINNING."},
	MissionFinal_BombDestroyed = {"EXPLOSIVE COMPROMISED. INEFFICIENT."},
	MissionFinal_BombArmed = {"DETONATION SEQUENCE ACTIVE. EVACUATION ADVISED."},

	PodIncoming = {"TIME POD DETECTED. RETRIEVAL REQUIRED."},
	PodResponse = {"SECURE POD INITATED"},
	PodCollected_Self = {"POD ACQUIRED. ORGANIC EXTRACTION COMPLETE.", "HUMAN SURVIVAL: ACCEPTABLE."},
	PodDestroyed_Obs = {"POD COMPROMISED. ORGANIC CASUALTY."},
	Secret_DeviceSeen_Mountain = {"UNKNOWN DEVICE PRESENT."},
	Secret_DeviceSeen_Ice = {"OBJECT DETECTED IN ICE."},
	Secret_DeviceUsed = {"ACTIVATING UNKNOWN TECHNOLOGY."},
	Secret_Arriving = {"ANOMALOUS TIME POD INCOMING."},
	Emerge_Detected = {"VEK EMERGENCE IMMINENT. PREPARED.", "TARGETS ACQUIRED.", "VEK DETECTED. INITIATING COMBAT PROTOCOLS."},
	Emerge_Success = {"VEK ARRIVAL CONFIRMED. ENGAGING."},
	Emerge_FailedMech = {"EMERGENCE BLOCKED. EFFICIENT."},
	Emerge_FailedVek = {"VEK BLOCKED. SATISFACTORY RESULT."},

	-- Mech State
	Mech_LowHealth = {"STRUCTURAL INTEGRITY COMPROMISED.", "DAMAGE LEVELS CRITICAL."},
	Mech_Webbed = {"MOBILITY RESTRICTED. UNACCEPTABLE.", "WEBBING DETECTED. INEFFICIENT."},
	Mech_Shielded = {"SHIELD ACTIVE. OPTIMAL."},
	Mech_Repaired = {"REPAIRS COMPLETE. RETURNING TO COMBAT.", "SYSTEMS OPTIMAL."},
	Pilot_Level_Self = {"COMBAT SUBROUTINES UPGRADED.", "WARBOT LEARNING PROTOCOLS ACTIVE.", "SKILL ACQUISITION COMPLETE. SUPERIORITY INCREASING."},
	Pilot_Level_Obs = {"UNIT #main_first IMPROVING. STILL INFERIOR TO WARBOT."},
	Mech_ShieldDown = {"SHIELD OFFLINE."},

	-- Damage Done
	Vek_Drown = {"VEK SUBMERGED. OPTIMAL OUTCOME."},
	Vek_Fall = {"GRAVITY KILL CONFIRMED."},
	Vek_Smoke = {"TACTICAL SMOKE DEPLOYED."},
	Vek_Frozen = {"VEK CRYOGENIC STATUS ACHIEVED."},
	VekKilled_Self = {"TARGET ELIMINATED.", "VEK DESTROYED.", "KILL CONFIRMED.", "HOSTILE ORGANIC NO LONGER OPERATIONAL", "EFFICIENCY CONFIRMED."},
	VekKilled_Obs = {"ORGANIC PILOT ELIMINATED THREAT. NOTED."},
	VekKilled_Vek = {"VEK ERROR DETECTED. EXPLOITABLE."},

	DoubleVekKill_Self = {"WARBOT TACTICAL SUPERIORITY EVIDENT.", "OPTIMAL EFFICIENCY."},
	DoubleVekKill_Obs = {"DOUBLE ELIMINATION BY #main_second. IMPRESSIVE FOR ORGANIC."},
	DoubleVekKill_Vek = {"OPERATING AT PEAK EFFICIENCY."},

	MntDestroyed_Self = {"OBSTACLE REMOVED.", "TERRAIN MODIFICATION SUCCESSFUL."},
	MntDestroyed_Obs = {"MOUNTAIN DESTROYED."},
	MntDestroyed_Vek = {"GEOLOGICAL IMPACT DETECTED."},

	PowerCritical = {"POWER GRID CRITICAL. EMERGENCY DEFENSE PROTOCOLS ACTIVE.", "GRID FAILURE UNACCEPTABLE. ENGAGING."},
	Bldg_Destroyed_Self = {"STRUCTURE DESTROYED. ERROR IN CALCULATIONS.", "BUILDING LOST. WARBOT EFFICIENCY DECREASED."},
	Bldg_Destroyed_Obs = {"CRITICAL STRUCTURE COMPROMISED."},
	Bldg_Destroyed_Vek = {"HOSTILE ORGANIC DESTROYED BUILDING. EXPECTED BEHAVIOR."},
	Bldg_Resisted = {"GRID DEFENSE OPERATING AT FULL POWER."},

	-- Shared Missions
	Mission_Train_TrainStopped = {"TRAIN HALTED."},
	Mission_Train_TrainDestroyed = {"TRAIN DESTROYED. INEFFICIENT."},
	Mission_Block_Reminder = {"VEK EMERGENCE BLOCKING REQUIRED."},

	-- Archive
	Mission_Airstrike_Incoming = {"AERIAL BOMBARDMENT DETECTED. REPOSITIONING."},
	Mission_Tanks_Activated = {"GROUND UNITS OPERATIONAL."},
	Mission_Tanks_PartialActivated = {"PARTIAL TANK ACTIVATION CONFIRMED."},
	Mission_Dam_Reminder = {"DAM STRUCTURAL INTEGRITY CRITICAL."},
	Mission_Dam_Destroyed = {"DAM COMPROMISED. FLOODING INITIATED."},
	Mission_Satellite_Destroyed = {"COMMUNICATIONS SATELLITE LOST."},
	Mission_Satellite_Imminent = {"SATELLITE LAUNCH SEQUENCE ACTIVE."},
	Mission_Satellite_Launch = {"SATELLITE DEPLOYED SUCCESSFULLY.", "COMMUNICATIONS RESTORED."},
	Mission_Mines_Vek = {"MINE ACTIVATION SUCCESSFUL."},

	-- RST
	Mission_Terraform_Destroyed = {"TERRAFORMING DEVICE DESTROYED."},
	Mission_Terraform_Attacks = {"TERRAFORMER HOSTILE ACTIVITY DETECTED."},
	Mission_Cataclysm_Falling = {"SEISMIC EVENT. GROUND COLLAPSE IMMINENT."},
	Mission_Lightning_Strike_Vek = {"NATURE TARGETING VEK. ELIMINATED."},
	Mission_Solar_Destroyed = {"SOLAR FACILITY DESTROYED."},
	Mission_Force_Reminder = {"MOUNTAIN OBSTACLES REQUIRE REMOVAL."},

	-- Pinnacle
	Mission_Freeze_Mines_Vek = {"FREEZE MINE EFFECTIVE. VEK IMMOBILIZED."},
	Mission_Factory_Destroyed = {"PRODUCTION FACILITY DESTROYED."},
	Mission_Factory_Spawning = {"FACTORY PRODUCING HOSTILE UNITS."},
	Mission_Reactivation_Thawed = {"VEK REACTIVATED."},
	Mission_SnowStorm_FrozenVek = {"VEK ENGAGED HIBERNATION PROTOCOL."},
	Mission_SnowStorm_FrozenMech = {"CONTROLS UNRESPONSIVE. REQUESTING ASSISTANCE."},
	BotKilled_Self = {"INFERIOR AI DESTROYED."},
	BotKilled_Obs = {"HOSTILE AI ELIMINATED."},

	-- Detritus
	Mission_Disposal_Destroyed = {"WASTE DISPOSAL COMPROMISED."},
	Mission_Disposal_Activated = {"DISPOSAL SYSTEM ACTIVE."},
	Mission_Barrels_Destroyed = {"ACID CONTAINMENT BREACH."},
	Mission_Power_Destroyed = {"POWER GENERATION FACILITY LOST."},
	Mission_Teleporter_Mech = {"TELEPORTATION COMPLETE. SYSTEMS NOMINAL.", "SPATIAL DISPLACEMENT ACHIEVED."},
	Mission_Belt_Mech = {"CONVEYOR DISPLACEMENT DETECTED.", "AUTOMATED TRANSPORT SYSTEM."},

	-- Additional mission triggers
	Mission_Airstrike_Arrival = {"AERIAL SUPPORT ARRIVING."},
	Mission_Snowstorm_FrozenVek = {"VEK SUSPENDED."},
	Mission_Shields_Down = {"VEK SHIELD DEACTIVATED. COMMENCE TARGETING"},
}
