local SkillEffectModifier = {}

-- Extend SkillActive class
setmetatable(SkillEffectModifier, { __index = more_plus.SkillActive })
SkillEffectModifier.__index = SkillEffectModifier

-- Initialize logger
SkillEffectModifier.DEBUG = false
local logger = memhack.logger
local SUBMODULE = logger.register("More+", "SkillEffectModifier", SkillEffectModifier.DEBUG)

-- Global list of all registered SkillEffectModifier instances
local registeredSkills = {}
-- Global event subscriptions
local globalEventSubscriptions = {}

function SkillEffectModifier:new(tbl)
	tbl = tbl or {}
	local obj = more_plus.SkillActive:new(tbl)
	setmetatable(obj, self)
	return obj
end

-- Register global callbacks once for all SkillEffectModifier skills
local function registerGlobalCallbacks()
	logger.logDebug(SUBMODULE, "Registering global SkillEffectModifier callbacks")

	table.insert(globalEventSubscriptions, modapiext.events.onSkillBuild:subscribe(
		function(mission, pawn, weaponId, p1, p2, skillEffect)
			SkillEffectModifier.processAllSkills(pawn, false, skillEffect, p2)
		end))
	table.insert(globalEventSubscriptions, modapiext.events.onFinalEffectBuild:subscribe(
		function(mission, pawn, weaponId, p1, p2, p3, skillEffect)
			SkillEffectModifier.processAllSkills(pawn, true, skillEffect, p2)
		end))

	logger.logDebug(SUBMODULE, "Registered %d global callbacks", #globalEventSubscriptions)
end

-- Unregister global callbacks when no skills remain
local function unregisterGlobalCallbacks()
	logger.logDebug(SUBMODULE, "Unregistering global SkillEffectModifier callbacks")

	for _, subscription in ipairs(globalEventSubscriptions) do
		subscription:unsubscribe()
	end
	globalEventSubscriptions = {}

	logger.logDebug(SUBMODULE, "Unregistered all global callbacks")
end

function SkillEffectModifier:setupEffect()
	logger.logDebug(SUBMODULE, "Setting up effect modifier for %s", self.id)

	-- If this is the first skill, register global callbacks
	if #registeredSkills == 0 then
		registerGlobalCallbacks()
	end

	-- Register this skill instance in the global list
	table.insert(registeredSkills, self)
	logger.logDebug(SUBMODULE, "Registered skill %s (total: %d)", self.id, #registeredSkills)
end

-- Override remove to cleanup from global list
function SkillEffectModifier:clearEvents()
	logger.logDebug(SUBMODULE, "Removing skill %s", self.id)

	-- Call parent's remove first
	more_plus.SkillActive.clearEvents(self)

	-- Remove this skill from the global registered list
	for i, skill in ipairs(registeredSkills) do
		if skill.id == self.id then
			table.remove(registeredSkills, i)
			logger.logDebug(SUBMODULE, "Removed skill %s from global list (remaining: %d)", self.id, #registeredSkills)
			break
		end
	end

	-- If no skills remain, unregister global callbacks
	if #registeredSkills == 0 then
		unregisterGlobalCallbacks()
	end
end

-- Hook for derived skills to modify space damage. Can optionally return an array of new SpaceDamage objects
-- to be added to the effect and re-processed
-- attackingPawn: The pawn performing the attack (if applicable)
-- previewState: The weapon preview state to use for icons
-- spaceDamage: The space damage being processed
-- indexes: The indexes of this skill on the pilot
-- targetPawn: The pawn at the damage location (if applicable)
function SkillEffectModifier:modifySpaceDamage(attackingPawn, previewState, spaceDamage, indexes, targetPawn)
	logger.logError(SUBMODULE, string.format("SkillEffectModifier modifySpaceDamage not implemented for skill %s", self.id))
end

-- Helper to get pawn at a location, checking temp positions first then board
function SkillEffectModifier:getPawnAt(loc, pawnPositions)
	local hash = more_plus.libs.boardUtils.getSpaceHash(loc)
	if pawnPositions[hash] ~= nil then
		return pawnPositions[hash]
	end
	return Board:GetPawn(loc)
end

-- Process a list of space damages and return any new damages generated by modifySpaceDamage
function SkillEffectModifier:processDamageList(attackingPawn, isFinalEffect, damageList, indexes, pawnPositions, pendingMoves, isQueued)
	local spaceDamagesToAdd = {}

	-- Calculate preview state once for all damages in this list
	local previewState = isFinalEffect and more_plus.libs.weaponPreview.STATE_FINAL_EFFECT or
			more_plus.libs.weaponPreview.STATE_SKILL_EFFECT
	if isQueued then
		-- TODO: No queued effect final?
		previewState = --isFinalEffect and more_plus.libs.weaponPreview.STATE_QUEUED_FINAL_EFFECT or
				more_plus.libs.weaponPreview.STATE_QUEUED_SKILL
	end

	for i, spaceDamage in ipairs(damageList) do
		-- If this is a movement, we need to track and update the temporary pawn positions
		if spaceDamage:IsMovement() then
			local moveStart = spaceDamage:MoveStart()
			local moveEnd = spaceDamage:MoveEnd()
			local movingPawn = self:getPawnAt(moveStart, pawnPositions)

			if movingPawn then
				table.insert(pendingMoves, {
					pawn = movingPawn,
					pawnId = movingPawn:GetId(),
					from = moveStart,
					to = moveEnd
				})
				logger.logDebug(SUBMODULE, "Tracked move for pawn %d from %s to %s",
					movingPawn:GetId(), moveStart:GetString(), moveEnd:GetString())
			end

			-- If there is a delay or its the last one, we add the pending to
			-- the updated positions. Otherwise it stays in pending as it will not
			-- be considered executed yet. This allows for swapping two pawns for example
			if spaceDamage.fDelay ~= 0 or i == #damageList then
				for _, moveData in ipairs(pendingMoves) do
					local fromHash = more_plus.libs.boardUtils.getSpaceHash(moveData.from)
					local toHash = more_plus.libs.boardUtils.getSpaceHash(moveData.to)
					pawnPositions[fromHash] = false
					pawnPositions[toHash] = moveData.pawn
				end
				pendingMoves = {}
			end
		-- if its not a movement, apply any pending moves and then call into our modify fn
		else
			if #pendingMoves > 0 then
				for _, moveData in ipairs(pendingMoves) do
					local fromHash = more_plus.libs.boardUtils.getSpaceHash(moveData.from)
					local toHash = more_plus.libs.boardUtils.getSpaceHash(moveData.to)
					pawnPositions[fromHash] = false
					pawnPositions[toHash] = moveData.pawn
				end
				pendingMoves = {}
			end

			local targetPawn = self:getPawnAt(spaceDamage.loc, pawnPositions)
			local additionalDamages = self:modifySpaceDamage(attackingPawn, previewState, spaceDamage, indexes, targetPawn)

			-- If modifySpaceDamage returns an array of space damages, collect them
			if additionalDamages and type(additionalDamages) == "table" then
				for _, newDamage in ipairs(additionalDamages) do
					table.insert(spaceDamagesToAdd, newDamage)
				end
			end
		end
	end

	return spaceDamagesToAdd
end

-- Helper function to process effects with a specific isQueued value
local function processEffectsWithQueuedFlag(attackingPawn, skillEffect, effectsTable, isQueued)
	if #effectsTable == 0 then
		logger.logDebug(SUBMODULE, "No effects to process for isQueued=%s", tostring(isQueued))
		return
	end

	-- Find all targeted pawns
	local allTargetedPawns = {}
	for _, spaceDamage in ipairs(effectsTable) do
		if not spaceDamage:IsMovement() then
			local targetPawn = Board:GetPawn(spaceDamage.loc)
			if targetPawn then
				allTargetedPawns[targetPawn:GetId()] = targetPawn
			end
		end
	end

	-- Build list of all skill+pawn combinations that apply
	local skillPawnCombos = {}
	for _, skill in ipairs(registeredSkills) do
		-- Check attacking pawn
		local attackingPilot = attackingPawn:GetPilot()
		if attackingPilot and cplus_plus_ex:isSkillOnPilot(skill.id, attackingPilot) then
			local indexes = cplus_plus_ex:getPilotSkillIndices(skill.id, attackingPilot)
			table.insert(skillPawnCombos, {
				skill = skill,
				pawn = attackingPawn,
				indexes = indexes,
				source = "attacker"
			})
			logger.logDebug(SUBMODULE, "Skill %s applies to attacking pawn %d (isQueued=%s)",
					skill.id, attackingPawn:GetId(), tostring(isQueued))
		end

		-- Check all targeted pawns
		for pawnId, targetPawn in pairs(allTargetedPawns) do
			local targetPilot = targetPawn:GetPilot()
			if targetPilot and cplus_plus_ex:isSkillOnPilot(skill.id, targetPilot) then
				-- Don't add duplicate if attacking pawn is also a target
				local alreadyAdded = false
				for _, existing in ipairs(skillPawnCombos) do
					if existing.skill.id == skill.id and existing.pawn:GetId() == targetPawn:GetId() then
						alreadyAdded = true
						break
					end
				end

				if not alreadyAdded then
					local indexes = cplus_plus_ex:getPilotSkillIndices(skill.id, targetPilot)
					table.insert(skillPawnCombos, {
						skill = skill,
						pawn = targetPawn,
						indexes = indexes,
						source = "target"
					})
					logger.logDebug(SUBMODULE, "Skill %s applies to targeted pawn %d (isQueued=%s)",
							skill.id, targetPawn:GetId(), tostring(isQueued))
				end
			end
		end
	end

	if #skillPawnCombos == 0 then
		logger.logDebug(SUBMODULE, "No skills apply to this effect (isQueued=%s)", tostring(isQueued))
		return
	end
	logger.logDebug(SUBMODULE, "Processing %d skill+pawn combinations (isQueued=%s)",
		#skillPawnCombos, tostring(isQueued))

	-- Loop through all skills, checking for new damages and repeating until no new damages
	local pawnPositions = {}
	local damagesToProcess = effectsTable
	local maxPasses = 10
	local currentPass = 0

	while damagesToProcess and #damagesToProcess > 0 and currentPass < maxPasses do
		local allNewDamages = {}
		local pendingMoves = {}

		-- Process ALL skill+pawn combinations for this pass
		for _, combo in ipairs(skillPawnCombos) do
			logger.logDebug(SUBMODULE, "Pass %d: Processing skill %s for pawn %d (%s, isQueued=%s)",
					currentPass, combo.skill.id, combo.pawn:GetId(), combo.source, tostring(isQueued))

			local newDamages = combo.skill:processDamageList(attackingPawn, isFinalEffect, damagesToProcess,
				combo.indexes, pawnPositions, pendingMoves, isQueued)

			if newDamages and #newDamages > 0 then
				for _, newDamage in ipairs(newDamages) do
					table.insert(allNewDamages, newDamage)
				end
			end
		end

		-- Add all new damages from this pass to the skill effect
		if #allNewDamages > 0 then
			for _, newDamage in ipairs(allNewDamages) do
				skillEffect:AddDamage(newDamage)
				logger.logDebug(SUBMODULE, "Added space damage at %s (pass %d, isQueued=%s)",
					newDamage.loc:GetString(), currentPass, tostring(isQueued))
			end

			-- Prepare for next pass with the new damages
			damagesToProcess = allNewDamages
			currentPass = currentPass + 1
		else
			-- No new damages, exit loop
			break
		end
	end

	-- Warn if we hit the max passes limit
	if currentPass >= maxPasses and damagesToProcess and #damagesToProcess > 0 then
		logger.logWarn(SUBMODULE, "Chaining effect limit reached (%d passes, isQueued=%s) with %d damages remaining",
				maxPasses, tostring(isQueued), #damagesToProcess)
	end
end

-- Global processing function that handles ALL registered skills together
function SkillEffectModifier.processAllSkills(attackingPawn, isFinalEffect, skillEffect, p2)
	if modApiExt_internal.nestedCall_GetSkillEffect or modApiExt_internal.nestedCall_GetFinalEffect then
		logger.logDebug(SUBMODULE, "Skipping nested call for SkillEffectModifier (GetSkillEffect: %s, GetFinalEffect: %s)",
				tostring(modApiExt_internal.nestedCall_GetSkillEffect), tostring(modApiExt_internal.nestedCall_GetFinalEffect))
		return
	end

	if not attackingPawn then
		logger.logDebug(SUBMODULE, "No attacking pawn found")
		return
	end

	-- Process regular effect with isQueued = false
	local regularEffects = extract_table(skillEffect.effect)
	if #regularEffects > 0 then
		logger.logDebug(SUBMODULE, "Processing %d regular effects", #regularEffects)
		processEffectsWithQueuedFlag(attackingPawn, skillEffect, regularEffects, false)
	end

	-- Process queued effect with isQueued = true
	if not skillEffect.q_effect:empty() then
		local queuedEffects = extract_table(skillEffect.q_effect)
		if #queuedEffects > 0 then
			logger.logDebug(SUBMODULE, "Processing %d queued effects", #queuedEffects)
			processEffectsWithQueuedFlag(attackingPawn, skillEffect, queuedEffects, true)
		end
	end
end

return SkillEffectModifier
