-- Dialog for Instructor Hale
-- Veteran NCO, crisp and practical, passes on hard-won field tricks

return {
	Gamestart = {"Alright. Watch what I do out there.", "I've picked up a few tricks. You'll see.", "Same war, new sector. Move out."},
	FTL_Found = {"Time device. Seen worse.", "Another relic. Grab it and keep moving."},
	FTL_Start = {"New timeline. Same fight.", "Reset the clock. Not the job."},
	Gamestart_PostVictory = {"Last run held. Don't get sloppy.", "We made it through. Keep that momentum."},
	Death_Revived = {"Back up. Still in this.", "Not done yet."},
	Death_Main = {"Keep them alive...", "Pass it on...", "Don't waste what I showed you..."},
	Death_Response = {"#main_first! Stay with us!", "Get #main_first back in the fight!"},
	Death_Response_AI = {"Unit down. Keep pushing."},
	TimeTravel_Win = {"Another line saved. Good.", "We bought them more time."},
	Gameover_Start = {"We're not folding. Regroup.", "Bad beat. Fix it and go again."},
	Gameover_Response = {"Reset. We know the board now."},

	Upgrade_PowerWeapon = {"Good. More punch out there.", "That'll put holes in 'em.", "Solid upgrade."},
	Upgrade_NoWeapon = {"Armor first. Smart.", "Live longer, fight longer."},
	Upgrade_PowerGeneric = {"Every edge counts.", "Good call."},

	MissionStart = {"Eyes up. Do what I do.", "Stay tight and watch the line.", "Here we go again.", "Pay attention and try to keep up!"},
	Mission_ResetTurn = {"Bad line. Run it again.", "Second try. Don't repeat that mistake."},
	MissionEnd_Dead = {"Clean sweep. That's the standard.", "All down. Good work.", "Objective done."},
	MissionEnd_Retreat = {"They're pulling back.", "Line held. Move on."},

	MissionFinal_Start = {"Big one. Everything on the table.", "Last push. No mistakes.", "This is why we drill."},
	MissionFinal_StartResponse = {"Ready."},
	MissionFinal_FallStart = {"Ground's going. Move."},
	MissionFinal_FallResponse = {"Keep fighting. Don't freeze."},
	MissionFinal_Pylons = {"Grid's secure."},
	MissionFinal_Bomb = {"Bomb's rolling. Cover it.", "Protect that payload."},
	MissionFinal_BombResponse = {"On the bomb."},
	MissionFinal_CaveStart = {"Into the nest. Stay sharp."},
	MissionFinal_BombDestroyed = {"Bomb's gone. New plan."},
	MissionFinal_BombArmed = {"Bomb's hot. Clear out."},

	PodIncoming = {"Pod incoming.", "Someone's coming in hot."},
	PodResponse = {"On the pod."},
	PodCollected_Self = {"You're with us now.", "Pod secure."},
	PodDestroyed_Obs = {"Lost the pod.", "Shoot."},
	Secret_DeviceSeen_Mountain = {"Something in that mountain.", "Mark it."},
	Secret_DeviceSeen_Ice = {"Something in the ice.", "Worth a look."},
	Secret_DeviceUsed = {"Activating it.", "Here goes."},
	Secret_Arriving = {"Another pod. Odd signal."},
	Emerge_Detected = {"Vek coming up. Mark locations.", "Emergence. Get ready.", "Incoming. Positions."},
	Emerge_Success = {"They're on the board. Engage.", "Contact."},
	Emerge_FailedMech = {"Blocked 'em good.", "That's how you choke a path."},
	Emerge_FailedVek = {"Blocked themselves. Fine by me."},

	Mech_LowHealth = {"Taking hits. Need cover.", "Armor's shot. Help me out."},
	Mech_Webbed = {"Webbed. Can't move.", "Stuck. Clear it."},
	Mech_Shielded = {"Shield up."},
	Mech_Repaired = {"Back in the fight.", "Good to go."},
	Pilot_Level_Self = {"New trick. Someone on the squad can use this.", "Picked something up. I'll pass it along.", "That's worth sharing."},
	Pilot_Level_Obs = {"#main_first's getting sharper.", "Good work, #main_first.", "#main_first earned a new edge."},
	Mech_ShieldDown = {"Shield's gone."},

	Vek_Drown = {"Water got 'em.", "Drowned."},
	Vek_Fall = {"Long drop.", "Gravity did the work."},
	Vek_Smoke = {"Smoke screen. Use it.", "Blind 'em."},
	Vek_Frozen = {"Frozen solid.", "On ice."},
	VekKilled_Self = {"Down.", "Target out.", "One less bug.", "Kill confirmed.", "Next."},
	VekKilled_Obs = {"Good shot, #main_second.", "Clean kill, #main_second.", "Nice, #main_second."},
	VekKilled_Vek = {"Bugs eating bugs.", "Their mistake."},

	DoubleVekKill_Self = {"Two down.", "Double tap."},
	DoubleVekKill_Obs = {"Hell of a play, #main_second.", "#main_second took two."},
	DoubleVekKill_Vek = {"Two for free.", "Not the sharpest."},

	MntDestroyed_Self = {"Mountain's gone.", "Cleared."},
	MntDestroyed_Obs = {"Mountain down.", "Terrain's changed."},
	MntDestroyed_Vek = {"That Vek broke the rock."},

	PowerCritical = {"Grid's critical. Hold the line.", "Power's dying. Protect the buildings."},
	Bldg_Destroyed_Self = {"Building down. My fault.", "We lost one.", "That shouldn't have happened."},
	Bldg_Destroyed_Obs = {"Structure lost. Watch the rest.", "Building gone."},
	Bldg_Destroyed_Vek = {"They got a building.", "Vek scored one."},
	Bldg_Resisted = {"Building held.", "Grid's still breathing."},

	Mission_Train_TrainStopped = {"Train stopped. Keep it covered.", "Hold the train."},
	Mission_Train_TrainDestroyed = {"Train's gone.", "Bad loss."},
	Mission_Block_Reminder = {"Block those sites.", "Keep their numbers down."},

	Mission_Airstrike_Incoming = {"Incoming strike. Clear the zone.", "Bombs away. Move."},
	Mission_Tanks_Activated = {"Tanks are up.", "Armor on our side."},
	Mission_Tanks_PartialActivated = {"Some tanks online.", "Partial support."},
	Mission_Dam_Reminder = {"Break that dam.", "Flood 'em out."},
	Mission_Dam_Destroyed = {"Dam's gone. Watch the water.", "Flood incoming."},
	Mission_Satellite_Destroyed = {"Satellite lost.", "Comms down."},
	Mission_Satellite_Imminent = {"Launch soon. Clear the pad.", "Satellite going up."},
	Mission_Satellite_Launch = {"Satellite away.", "Launch good."},
	Mission_Mines_Vek = {"Mine got 'em.", "Good placement."},

	Mission_Terraform_Destroyed = {"Terraformer down.", "Threat cleared."},
	Mission_Terraform_Attacks = {"Watch that terraformer.", "It's shooting."},
	Mission_Cataclysm_Falling = {"Ground's giving way.", "Watch your footing."},
	Mission_Lightning_Strike_Vek = {"Lightning took one.", "I'll take it."},
	Mission_Solar_Destroyed = {"Solar array gone.", "Power hit."},
	Mission_Force_Reminder = {"Clear those mountains.", "Blast a path."},

	Mission_Freeze_Mines_Vek = {"Freeze mine worked.", "Bug's stuck."},
	Mission_Factory_Destroyed = {"Factory down.", "Good."},
	Mission_Factory_Spawning = {"Factory's spawning.", "Take it out."},
	Mission_Reactivation_Thawed = {"It's back up.", "Vek's moving again."},
	Mission_SnowStorm_FrozenVek = {"Storm froze one.", "Free shot."},
	Mission_SnowStorm_FrozenMech = {"Controls are frozen.", "I'm stuck. Cover me."},
	BotKilled_Self = {"Bot down.", "Lost the unit."},
	BotKilled_Obs = {"Friendly bot gone.", "Waste of metal."},

	Mission_Disposal_Destroyed = {"Disposal's gone.", "We're exposed."},
	Mission_Disposal_Activated = {"Disposal's running. Stay back.", "Nasty stuff out there."},
	Mission_Barrels_Destroyed = {"Acid spill. Watch your step.", "Corrosive leak."},
	Mission_Power_Destroyed = {"Power station lost.", "Can't afford another."},
	Mission_Teleporter_Mech = {"Teleported. Still hate that.", "Made it through."},
	Mission_Belt_Mech = {"Belt took me.", "Relocating."},

	Mission_Airstrike_Arrival = {"Air support inbound.", "Make room."},
	Mission_Snowstorm_FrozenVek = {"Another one frozen.", "Easy pick."},
	Mission_Shields_Down = {"Shields down. Hit 'em.", "They're exposed."},
}
